version: 0.2

environment_variables:
  plaintext:
    HUGO_VERSION: "0.110.0"
    
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - cd /tmp
      - git init
      - git submodule init
      - git submodule update --recursive
      - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
      - tar -xzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
      - mv hugo /usr/bin/hugo
      - cd -/Labs/Lab3/ 
      - rm -rf /tmp/*
  build:
    commands:
      - rm -rf public
      - hugo
      - aws s3 sync public/ s3://ids721c1bucket2/ --region us-east-1 --delete
  post_build:
    commands:
      - echo Build completed on `date`